[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.1",
    "pydantic-ai-slim[openai,google,mistral]>=1.90.0",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.27",
    "sentence-transformers>=5.4.1",
    "sqlite-vec>=0.1.9",
    "sse-starlette>=3.4.1",
    "uvicorn[standard]>=0.46.0",
]
